### PR TITLE
Update easy_time.jinja

### PR DESCRIPTION
**Pull request by kai-zer-ru**
Add russian translate

### CODE REVIEW

**Comment by bonoirk** [comment]
It seems to me that it is not enough just to add translations of words. An algorithm is needed to substitute words depending on the number. Something like this:

{% macro endings(number,endings) %}
  {%- set cases = [2, 0, 1, 1, 1, 2] %}
  {%- if (number % 100 > 4 and number % 100 < 20) == true %}
    {%- set version = 2 %}
  {%- else %}
    {%- set version = cases[min(number % 10, 5)] %}
  {%- endif %}
{{- endings[version] }}
{%- endmacro %}
{# ------- test --------#}
{% for i in range(1,21) %}
{{ i~' '~endings(i,['минуту', 'минуты', 'минут']) }}
{% endfor %}

**Comment by Petro31** [comment]
> It seems to me that it is not enough just to add translations of words. An algorithm is needed to substitute words depending on the number. Something like this:
> 
> {% macro endings(number,endings) %} {%- set cases = [2, 0, 1, 1, 1, 2] %} {%- if (number % 100 > 4 and number % 100 < 20) == true %} {%- set version = 2 %} {%- else %} {%- set version = cases[min(number % 10, 5)] %} {%- endif %} {{- endings[version] }} {%- endmacro %} {# ------- test --------#} {% for i in range(1,21) %} {{ i~' '~endings(i,['минуту', 'минуты', 'минут']) }} {% endfor %}

are there different words for 0, 1, 2 through 4, and greater than 4?

**Comment by Masterz69** [comment]
> are there different words for 0, 1, 2 through 4, and greater than 4?

Exactly. Not only for minutes, but for each & every unit.

**Comment by Petro31** [comment]
This was merged with @ildar170975's PR instead.

**Pull request closed without merging**
